import{randomUUID}from'node:crypto'
import type{DB}from'./db.ts'

export class SampleSlotError extends Error{code:string;errorCode:string;httpStatus:number;httpCode:number;constructor(code:string,status:number,message:string){super(message);this.code=this.errorCode=code;this.httpStatus=this.httpCode=status}}
type Plan={matrix:string;items:string[];qty:number}[]
const parse=<T>(value:string,fallback:T):T=>{try{return JSON.parse(value)}catch{return fallback}}
const letters:Record<string,string>={废水:'W',地表水:'S',地下水:'G',饮用水:'D',环境空气:'A',废气:'F',土壤:'T',噪声:'N',固废:'H',海水:'M'}
function nextOfficialId(db:DB,matrix:string,date:string){const prefix=`${letters[matrix]||'X'}${date.replaceAll('-','').slice(2)}-`,tails=(db.prepare(`SELECT id FROM samples WHERE id LIKE ?`).all(prefix+'%')as any[]).map(row=>String(row.id).slice(prefix.length)),last=tails.reduce((max,value)=>/^0+$/.test(value)?max:Math.max(max,parseInt(value,10)||0),0);return prefix+String(last+1)}
export function temporaryQrPayload(temporaryId:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(temporaryId))throw new SampleSlotError('TEMPORARY_ID_INVALID',422,'临时标识无效');return`TC1:${temporaryId.toLowerCase()}`}
export function ensureSampleSlots(db:DB,roundId:string,plan:Plan,uuid:()=>string=randomUUID){
  const at=new Date().toISOString(),wanted=new Map<string,{qty:number;items:string[]}>()
  for(const item of plan){const matrix=String(item.matrix||'样品'),current=wanted.get(matrix);wanted.set(matrix,{qty:(current?.qty??0)+Math.max(0,Number(item.qty)||0),items:[...new Set([...(current?.items??[]),...(item.items??[]).map(String)])]})}
  db.exec('BEGIN IMMEDIATE');try{
    const existing=db.prepare(`SELECT * FROM mobile_sample_slots WHERE round_id=? ORDER BY matrix,sequence`).all(roundId) as any[]
    for(const [matrix,target]of wanted){const rows=existing.filter(row=>row.matrix===matrix),active=rows.filter(row=>row.state==='active'&&!row.parent_slot_id),kept=active.slice(0,target.qty),removed=active.slice(target.qty);for(const row of kept)db.prepare(`UPDATE mobile_sample_slots SET items=? WHERE sample_slot_id=?`).run(JSON.stringify(target.items),row.sample_slot_id);for(const row of removed)if(!row.official_sample_id)db.prepare(`UPDATE mobile_sample_slots SET state='voided',voided_at=? WHERE sample_slot_id=?`).run(at,row.sample_slot_id);let sequence=rows.reduce((max,row)=>Math.max(max,Number(row.sequence)||0),0);for(let count=kept.length;count<target.qty;count++){sequence++;db.prepare(`INSERT INTO mobile_sample_slots(sample_slot_id,temporary_id,round_id,matrix,items,sequence,state,created_at) VALUES(?,?,?,?,?,?,'active',?)`).run(uuid(),uuid(),roundId,matrix,JSON.stringify(target.items),sequence,at)}}
    for(const row of existing)if(!wanted.has(row.matrix)&&row.state==='active'&&!row.official_sample_id)db.prepare(`UPDATE mobile_sample_slots SET state='voided',voided_at=? WHERE sample_slot_id=?`).run(at,row.sample_slot_id)
    db.exec('COMMIT')
  }catch(error){db.exec('ROLLBACK');throw error}
  return(db.prepare(`SELECT * FROM mobile_sample_slots WHERE round_id=? AND state='active' ORDER BY matrix,sequence`).all(roundId)as any[]).map(row=>({sampleSlotId:row.sample_slot_id,temporaryId:row.temporary_id,qrPayload:temporaryQrPayload(row.temporary_id),matrix:row.matrix,items:parse(row.items,[]),state:row.state,parentSlotId:row.parent_slot_id,officialSampleId:row.official_sample_id}))
}

export function materializeSampleSlots(db:DB,roundId:string,samplingDate:string,actor:{name:string;username?:string},manageTransaction=true){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(samplingDate)||new Date(`${samplingDate}T00:00:00Z`).toISOString().slice(0,10)!==samplingDate)throw new SampleSlotError('SAMPLING_DATE_INVALID',422,'采样日期无效')
  const round=db.prepare(`SELECT r.*,c.client FROM rounds r JOIN contracts c ON c.id=r.contract_id WHERE r.id=?`).get(roundId)as any;if(!round)throw new SampleSlotError('ROUND_NOT_FOUND',404,'期次不存在')
  const planned=String(round.plan_date||round.due_date),delta=Math.abs(Date.parse(`${samplingDate}T00:00:00Z`)-Date.parse(`${planned}T00:00:00Z`));if(!Number.isFinite(delta)||delta>7*86400_000)throw new SampleSlotError('SAMPLING_DATE_OUT_OF_WINDOW',409,'采样日期超出允许窗口')
  const slots=db.prepare(`SELECT * FROM mobile_sample_slots WHERE round_id=? AND state='active' ORDER BY matrix,sequence`).all(roundId)as any[],at=new Date().toISOString(),result:any[]=[]
  if(manageTransaction)db.exec('BEGIN IMMEDIATE');try{for(const slot of slots){if(slot.official_sample_id){result.push({sampleSlotId:slot.sample_slot_id,officialSampleId:slot.official_sample_id});continue}const officialSampleId=nextOfficialId(db,slot.matrix,samplingDate),items=slot.items;db.prepare(`INSERT INTO samples(id,client,matrix,items,status,note,contract_id,round_id,source,created_at) VALUES(?,?,?,?, 'pending','',?,?,'field',?)`).run(officialSampleId,round.client,slot.matrix,items,round.contract_id,roundId,at);db.prepare(`INSERT INTO sample_handovers(sample_id,action,from_person,to_person,condition,note,who,username,at) VALUES(?,'采样交接',?,NULL,NULL,?,?,?,?)`).run(officialSampleId,actor.name,`临时标识 ${slot.temporary_id}`,actor.name,actor.username??null,at);db.prepare(`UPDATE mobile_sample_slots SET official_sample_id=? WHERE sample_slot_id=? AND official_sample_id IS NULL`).run(officialSampleId,slot.sample_slot_id);result.push({sampleSlotId:slot.sample_slot_id,officialSampleId})}if(manageTransaction)db.exec('COMMIT');return result}catch(error){if(manageTransaction)db.exec('ROLLBACK');throw error}
}

export function splitSampleSlot(db:DB,parentSlotId:string,uuid:()=>string=randomUUID){const parent=db.prepare(`SELECT * FROM mobile_sample_slots WHERE sample_slot_id=?`).get(parentSlotId)as any;if(!parent||parent.state!=='active'||parent.official_sample_id)throw new SampleSlotError('SAMPLE_SLOT_NOT_SPLITTABLE',409,'该槽位不能拆分');const sequence=Number((db.prepare(`SELECT MAX(sequence) n FROM mobile_sample_slots WHERE round_id=? AND matrix=?`).get(parent.round_id,parent.matrix)as any).n||0)+1,id=uuid(),temporaryId=uuid(),at=new Date().toISOString();db.prepare(`INSERT INTO mobile_sample_slots(sample_slot_id,temporary_id,round_id,matrix,items,sequence,state,parent_slot_id,created_at) VALUES(?,?,?,?,?,?,'active',?,?)`).run(id,temporaryId,parent.round_id,parent.matrix,parent.items,sequence,parentSlotId,at);return{sampleSlotId:id,temporaryId,qrPayload:temporaryQrPayload(temporaryId),matrix:parent.matrix,items:parse(parent.items,[]),state:'active',parentSlotId,officialSampleId:null}}
export function voidSampleSlot(db:DB,sampleSlotId:string,at=new Date()){const result=db.prepare(`UPDATE mobile_sample_slots SET state='voided',voided_at=? WHERE sample_slot_id=? AND official_sample_id IS NULL AND state='active'`).run(at.toISOString(),sampleSlotId)as any;if(!result.changes)throw new SampleSlotError('SAMPLE_SLOT_NOT_VOIDABLE',409,'该槽位不能作废')}
