import{createHash}from'node:crypto'
import type{DB}from'./db.ts'
import{currentOfflineTaskScope,reauthenticate,type User}from'./handlers.ts'
import{finalizeSubmission,SubmissionError,type SubmissionRecord}from'./submissions.ts'
import{materializeSampleSlots}from'./mobileSampleSlots.ts'

function parse<T>(value:string,fallback:T):T{try{return JSON.parse(value)}catch{return fallback}}
export function submissionSummaryHash(record:SubmissionRecord){return createHash('sha256').update(JSON.stringify({roundId:record.roundId,taskVersion:record.taskVersion,draftRevision:record.draftRevision,ruleVersion:record.ruleVersion,payloadHash:record.payloadHash,attachmentReceipts:[...record.attachmentReceipts].sort()})).digest('hex')}
function record(db:DB,id:string){const row=db.prepare(`SELECT * FROM mobile_submissions WHERE client_submission_id=?`).get(id)as any;if(!row)throw new SubmissionError('SUBMISSION_NOT_FOUND',404,'提交不存在');return{clientSubmissionId:row.client_submission_id,receiptId:row.receipt_id,roundId:row.round_id,ownerId:row.owner_id,deviceId:row.device_id,taskVersion:row.task_version,ruleVersion:row.rule_version,draftRevision:row.draft_revision,canonicalPayload:row.canonical_payload,payloadHash:row.payload_hash,attachmentReceipts:parse(row.attachment_receipts,[]),status:row.status,publication:row.publication_json?parse(row.publication_json,null):null,errorCode:row.error_code,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at}as SubmissionRecord}
export function publishConfirmedSubmission(db:DB,submission:SubmissionRecord){const round=db.prepare(`SELECT sampler_ids,assignment_status FROM rounds WHERE id=?`).get(submission.roundId)as any,assigned=parse<string[]>(round?.sampler_ids||'[]',[]),scope=currentOfflineTaskScope(db,submission.roundId),summaryHash=submissionSummaryHash(submission);if(!round||round.assignment_status!=='active'||scope.taskVersion!==submission.taskVersion||scope.ruleVersion!==submission.ruleVersion)throw new SubmissionError('CONFIRMATION_SCOPE_STALE',409,'确认范围已变化');const confirmedBy=(db.prepare(`SELECT confirmer_id FROM mobile_submission_confirmations WHERE client_submission_id=? AND task_version=? AND draft_revision=? AND rule_version=? AND summary_hash=? ORDER BY confirmed_at`).all(submission.clientSubmissionId,submission.taskVersion,submission.draftRevision,submission.ruleVersion,summaryHash)as any[]).map(row=>row.confirmer_id).filter(id=>assigned.includes(id));if(new Set(confirmedBy).size<2)throw new SubmissionError('TWO_CONFIRMATIONS_REQUIRED',409,'尚未完成两人确认');const confirmer=db.prepare(`SELECT name,username FROM users WHERE username=?`).get(confirmedBy[confirmedBy.length-1])as any,payload=parse<any>(submission.canonicalPayload,null);return{samples:materializeSampleSlots(db,submission.roundId,String(payload.global.samplingDate),confirmer,false),summaryHash,confirmedBy:[...new Set(confirmedBy)].sort()}}
export function confirmMobileSubmission(db:DB,id:string,actor:User,password:string,now=()=>new Date(),requestProof?:{deviceId:string;nonce:string;issuedAt:string;expiresAt:string},allowDifferentManagedDevice=false){
  const submission=record(db,id)
  const round=db.prepare(`SELECT sampler_ids,assignment_status FROM rounds WHERE id=?`).get(submission.roundId)as any,assigned=parse<string[]>(round?.sampler_ids||'[]',[])
  if(!round||round.assignment_status!=='active'||!actor.roles.includes('sampler')||actor.status!=='active'||!assigned.includes(actor.username)||new Set(assigned).size<2)throw new SubmissionError('TWO_PERSON_ASSIGNMENT_REQUIRED',403,'需要两名当前受派采样员')
  reauthenticate(db,actor.username,password,now().getTime())
  const scope=currentOfflineTaskScope(db,submission.roundId);if(scope.taskVersion!==submission.taskVersion)throw new SubmissionError('TASK_VERSION_CONFLICT',409,'任务版本已变化');if(scope.ruleVersion!==submission.ruleVersion)throw new SubmissionError('RULE_VERSION_RETIRED',409,'规则版本已变化')
  if(requestProof&&!allowDifferentManagedDevice&&requestProof.deviceId!==submission.deviceId)throw new SubmissionError('CONFIRMATION_DEVICE_MISMATCH',403,'确认必须在原受管设备完成')
  const summaryHash=submissionSummaryHash(submission),at=now().toISOString();db.exec('BEGIN IMMEDIATE');try{if(requestProof)db.prepare(`INSERT INTO device_request_nonces(device_id,nonce,issued_at,expires_at)VALUES(?,?,?,?)`).run(requestProof.deviceId,requestProof.nonce,requestProof.issuedAt,requestProof.expiresAt);db.prepare(`INSERT OR IGNORE INTO mobile_submission_confirmations(client_submission_id,confirmer_id,round_id,task_version,draft_revision,rule_version,summary_hash,confirmed_at)VALUES(?,?,?,?,?,?,?,?)`).run(id,actor.username,submission.roundId,submission.taskVersion,submission.draftRevision,submission.ruleVersion,summaryHash,at);db.exec('COMMIT')}catch(error:any){db.exec('ROLLBACK');if(/device_request_nonces|UNIQUE constraint/.test(error?.message||''))throw new SubmissionError('DEVICE_PROOF_REPLAY',409,'设备请求证明已使用');throw error}
  const valid=(db.prepare(`SELECT confirmer_id FROM mobile_submission_confirmations WHERE client_submission_id=? AND task_version=? AND draft_revision=? AND rule_version=? AND summary_hash=?`).all(id,submission.taskVersion,submission.draftRevision,submission.ruleVersion,summaryHash)as any[]).map(row=>row.confirmer_id).filter(user=>assigned.includes(user))
  if(new Set(valid).size<2)return{...record(db,id),confirmationCount:new Set(valid).size,summaryHash}
  const ownerRow=db.prepare(`SELECT username,name,roles,status,created_at,must_change_pw FROM users WHERE username=?`).get(submission.ownerId)as any;if(!ownerRow)throw new SubmissionError('SUBMISSION_OWNER_MISSING',409,'提交人不存在');ownerRow.roles=parse(ownerRow.roles,[])
  const completed=finalizeSubmission(db,id,ownerRow,{now,publish:publishConfirmedSubmission})
  return{...completed,confirmationCount:2,summaryHash}
}

export function pendingConfirmationSnapshot(db:DB,roundId:string,actor:User){const round=db.prepare(`SELECT sampler_ids,assignment_status FROM rounds WHERE id=?`).get(roundId)as any,assigned=parse<string[]>(round?.sampler_ids||'[]',[]);if(!round||round.assignment_status!=='active'||!assigned.includes(actor.username))throw new SubmissionError('SUBMISSION_NOT_FOUND',404,'没有待确认提交');const row=db.prepare(`SELECT client_submission_id FROM mobile_submissions WHERE round_id=? AND status IN ('pending','finalizing') ORDER BY created_at DESC LIMIT 1`).get(roundId)as any;if(!row)throw new SubmissionError('SUBMISSION_NOT_FOUND',404,'没有待确认提交');const submission=record(db,row.client_submission_id),summaryHash=submissionSummaryHash(submission),confirmedBy=(db.prepare(`SELECT confirmer_id FROM mobile_submission_confirmations WHERE client_submission_id=? AND summary_hash=? ORDER BY confirmed_at`).all(submission.clientSubmissionId,summaryHash)as any[]).map(row=>row.confirmer_id);return{clientSubmissionId:submission.clientSubmissionId,receiptId:submission.receiptId,roundId,status:submission.status,taskVersion:submission.taskVersion,draftRevision:submission.draftRevision,ruleVersion:submission.ruleVersion,payloadHash:submission.payloadHash,summaryHash,assignedIds:assigned,confirmedBy,snapshot:parse(submission.canonicalPayload,null)}}
