<script setup lang="ts">
import { ref } from 'vue'
import { api, currentUser } from '../api'
import { ManagedDeviceKeyStore } from '../offline/managedDevice'

const qrPayload=ref(''),password=ref(''),claim=ref<any>(null),message=ref(''),busy=ref(false)
async function sha256(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function readInvite(){if(!qrPayload.value||busy.value)return;busy.value=true;message.value='';try{claim.value=await api.claimMobileConfirmationInvite(qrPayload.value.trim());message.value='已读取冻结摘要。此页面只能核对和确认，不能修改现场记录。'}catch(error:any){message.value=error?.response?.data?.error||'确认码无效、已过期或不属于当前人员'}finally{busy.value=false}}
async function confirm(){if(!claim.value?.confirmation||!password.value||!currentUser.value||busy.value)return;busy.value=true;message.value='';try{const c=claim.value.confirmation,body={password:password.value},path=`/api/mobile-confirmation-claims/${encodeURIComponent(claim.value.claimId)}/confirm`,proof=await new ManagedDeviceKeyStore().signRequest(claim.value.deviceBinding.publicKeySpki,claim.value.deviceBinding.fingerprint,{method:'POST',path,actor:currentUser.value.username,roundId:c.roundId,attachmentId:c.clientSubmissionId,mime:'application/json',bodyHash:await sha256(JSON.stringify(body)),contentRevision:Number(c.draftRevision),taskVersion:c.taskVersion,ruleVersion:c.ruleVersion});const result=await api.confirmMobileConfirmationClaim(claim.value.claimId,password.value,Number(c.draftRevision),proof);password.value='';message.value=result.receiptStatus==='complete'?'双人确认完成，正式回执已生成':'本次确认已记录，等待另一名人员确认';claim.value={...claim.value,status:'used'}}catch(error:any){message.value=error?.response?.data?.error||'确认失败；可查询领取状态后重试，不会重复提交'}finally{busy.value=false}}
</script>

<template><main class="confirmation-page"><section class="card"><p class="eyebrow">第二设备 · 只读确认</p><h1>核对冻结采样摘要</h1><p>扫描后只显示已冻结内容；本页面没有编辑、拍照或删除入口。</p><label>扫码结果或确认码<textarea v-model="qrPayload" rows="3" placeholder="MC1:…" /></label><button type="button" :disabled="busy||!qrPayload" @click="readInvite">读取确认内容</button><p v-if="message" role="status" class="notice">{{ message }}</p></section><section v-if="claim?.confirmation" class="card summary" aria-label="冻结摘要"><h2>冻结摘要</h2><dl><div><dt>摘要指纹</dt><dd>{{ claim.confirmation.summaryHash }}</dd></div><div><dt>任务版本</dt><dd>{{ claim.confirmation.taskVersion }}</dd></div><div><dt>规则版本</dt><dd>{{ claim.confirmation.ruleVersion }}</dd></div><div><dt>草稿修订</dt><dd>{{ claim.confirmation.draftRevision }}</dd></div></dl><pre>{{ JSON.stringify(claim.confirmation.snapshot,null,2) }}</pre><label>当前人员密码<input v-model="password" type="password" autocomplete="current-password" /></label><button type="button" :disabled="busy||!password||claim.status==='used'" @click="confirm">{{ claim.status==='used'?'已使用':'确认此冻结摘要' }}</button></section></main></template>

<style scoped>.confirmation-page{min-height:100vh;padding:24px;background:#f3f0ea;color:#1e2329;color-scheme:light;font-family:"Source Han Sans SC","Noto Sans SC","PingFang SC",sans-serif}.card{box-sizing:border-box;width:min(760px,100%);margin:0 auto 20px;padding:24px;border:1px solid #cbc5ba;border-radius:10px;background:#fffefc}.eyebrow{color:#62676e;font-weight:700}.card label{display:grid;gap:8px;margin:18px 0;font-weight:700}textarea,input{box-sizing:border-box;width:100%;min-height:48px;padding:12px;border:1px solid #a9a297;border-radius:6px;background:#fff;color:#1e2329;font:inherit}button{min-height:52px;padding:0 20px;border:0;border-radius:7px;background:#4f46e5;color:#fff;font:inherit;font-weight:700}button:disabled{opacity:.55}.notice{padding:12px;border-left:4px solid #176b5b;background:#e8f4f0}.summary dl{display:grid;gap:8px}.summary dl div{display:grid;grid-template-columns:120px 1fr}.summary dd{margin:0;overflow-wrap:anywhere;font-family:ui-monospace,monospace}.summary pre{max-height:360px;overflow:auto;padding:16px;border:1px solid #cbc5ba;background:#f7f4ee;white-space:pre-wrap}@media(max-width:600px){.confirmation-page{padding:12px}.card{padding:18px}.summary dl div{grid-template-columns:1fr}}</style>
